import type { Employee } from "./types";

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "1",
    firstName: "Alice",
    lastName: "Chen",
    email: "alice@company.com",
    department: "Engineering",
    phone: "+1-555-0101",
  },
  {
    id: "2",
    firstName: "Bob",
    lastName: "Smith",
    email: "bob@company.com",
    department: "Sales",
    phone: "+1-555-0102",
  },
  {
    id: "3",
    firstName: "Carol",
    lastName: "Wu",
    email: "carol@company.com",
    department: "Design",
    phone: "+1-555-0103",
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Park",
    email: "david@company.com",
    department: "Engineering",
    phone: "+1-555-0104",
  },
  {
    id: "5",
    firstName: "Emma",
    lastName: "Jones",
    email: "emma@company.com",
    department: "HR",
  },
  {
    id: "6",
    firstName: "Frank",
    lastName: "Martinez",
    email: "frank@company.com",
    department: "Marketing",
    phone: "+1-555-0106",
  },
  {
    id: "7",
    firstName: "Grace",
    lastName: "Lee",
    email: "grace@company.com",
    department: "Finance",
    phone: "+1-555-0107",
  },
  {
    id: "8",
    firstName: "Henry",
    lastName: "Taylor",
    email: "henry@company.com",
    department: "Engineering",
    phone: "+1-555-0108",
  },
  {
    id: "9",
    firstName: "Iris",
    lastName: "Anderson",
    email: "iris@company.com",
    department: "Sales",
  },
  {
    id: "10",
    firstName: "Jack",
    lastName: "Wilson",
    email: "jack@company.com",
    department: "Design",
    phone: "+1-555-0110",
  },
  {
    id: "11",
    firstName: "Karen",
    lastName: "Brown",
    email: "karen@company.com",
    department: "Engineering",
    phone: "+1-555-0111",
  },
  {
    id: "12",
    firstName: "Leo",
    lastName: "Garcia",
    email: "leo@company.com",
    department: "Marketing",
  },
  {
    id: "13",
    firstName: "Maya",
    lastName: "Rodriguez",
    email: "maya@company.com",
    department: "HR",
    phone: "+1-555-0113",
  },
  {
    id: "14",
    firstName: "Nathan",
    lastName: "Kim",
    email: "nathan@company.com",
    department: "Finance",
    phone: "+1-555-0114",
  },
  {
    id: "15",
    firstName: "Olivia",
    lastName: "Nguyen",
    email: "olivia@company.com",
    department: "Engineering",
  },
  {
    id: "16",
    firstName: "Peter",
    lastName: "Johnson",
    email: "peter@company.com",
    department: "Sales",
    phone: "+1-555-0116",
  },
  {
    id: "17",
    firstName: "Quinn",
    lastName: "Davis",
    email: "quinn@company.com",
    department: "Design",
    phone: "+1-555-0117",
  },
  {
    id: "18",
    firstName: "Rachel",
    lastName: "Miller",
    email: "rachel@company.com",
    department: "Marketing",
  },
  {
    id: "19",
    firstName: "Sam",
    lastName: "White",
    email: "sam@company.com",
    department: "Engineering",
    phone: "+1-555-0119",
  },
  {
    id: "20",
    firstName: "Tina",
    lastName: "Lopez",
    email: "tina@company.com",
    department: "HR",
    phone: "+1-555-0120",
  },
  {
    id: "21",
    firstName: "Uma",
    lastName: "Patel",
    email: "uma@company.com",
    department: "Finance",
  },
  {
    id: "22",
    firstName: "Victor",
    lastName: "Chang",
    email: "victor@company.com",
    department: "Sales",
    phone: "+1-555-0122",
  },
  {
    id: "23",
    firstName: "Wendy",
    lastName: "Thompson",
    email: "wendy@company.com",
    department: "Engineering",
    phone: "+1-555-0123",
  },
  {
    id: "24",
    firstName: "Xavier",
    lastName: "Harris",
    email: "xavier@company.com",
    department: "Design",
  },
];
